apiVersion: apps/v1
kind: Deployment
metadata:
  name: ateng-boot
  namespace: ateng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ateng-boot
  template:
    metadata:
      labels:
        app: ateng-boot
    spec:
      hostname: ateng-boot
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: ateng-boot
                topologyKey: kubernetes.io/hostname
      containers:
        - name: ateng-boot
          image: registry.lingo.local/ateng/ateng-boot:latest
          imagePullPolicy: Always
          ports:
            - name: tcp-20420
              protocol: TCP
              containerPort: 20420
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx2048m -Dspring.profiles.active=dev"
          #resources:
          #  limits:
          #    cpu: '2'
          #    memory: 2Gi
          #  requests:
          #    cpu: 500m
          #    memory: 512Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 20420
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 20420
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "curl -u admin:Admin@123 -X POST http://localhost:20420/actuator/shutdown && sleep 25" ]
---
apiVersion: v1
kind: Service
metadata:
  name: ateng-boot
  namespace: ateng
  labels:
    app: ateng-boot
spec:
  type: NodePort
  selector:
    app: ateng-boot
  ports:
    - port: 20420
      targetPort: 20420
      nodePort: 20420
---
